AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        # AllowCredentials: true
  BetsyAPIGroups:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: betsy-backend/
      Handler: app.groupsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GroupsList:
          Type: Api
          Properties:
            Path: /groups
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        GroupGet:
          Type: Api
          Properties:
            Path: /groups/{id}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
  BetsyAPIUsers:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: betsy-backend/
      Handler: app.usersHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        UsersList:
          Type: Api
          Properties:
            Path: /users
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        UserGet:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        UserLogin:
          Type: Api
          Properties:
            Path: /users/login
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        UserSubscription:
          Type: Api
          Properties:
            Path: /users/{id}/sub
            Method: post
            RestApiId:
              Ref: ApiGatewayApi

  BetsyAPITasks:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: betsy-backend/
      Handler: app.tasksHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        TasksList:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        TaskGet:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        TaskGetBets:
          Type: Api
          Properties:
            Path: /tasks/{id}/bets
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        TaskUpdate:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: post
            RestApiId:
              Ref: ApiGatewayApi

  BetsyAPIBets:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: betsy-backend/
      Handler: app.betsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        BetsList:
          Type: Api
          Properties:
            Path: /bets
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        BetGet:
          Type: Api
          Properties:
            Path: /bets/{id}
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        BetUpdate:
          Type: Api
          Properties:
            Path: /bets/{id}
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        BetCreate:
          Type: Api
          Properties:
            Path: /bets
            Method: post
            RestApiId:
              Ref: ApiGatewayApi

  BetsyAPIActions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: betsy-backend/
      Handler: app.actionsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ActionsCreateTaskWithBet:
          Type: Api
          Properties:
            Path: /actions/create_task_with_bet
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        ActionsSetTaskState:
          Type: Api
          Properties:
            Path: /actions/set_task_state
            Method: post
            RestApiId:
              Ref: ApiGatewayApi

    Metadata: # Manage esbuild properties
      BuildProperties:
        UseNpmCi: True
