sources:
  - name: bets
    handler:
      mysql:
        # You can use environment variables like
        # host: "{env.MYSQL_HOST}"
        # port: "{env.MYSQL_PORT}"
        # user: "{env.MYSQL_USER}"
        # password: "{env.MYSQL_PASSWORD}"
        # database: "{env.MYSQL_DATABASE}"
        host: betsy.c9wzmnw9mmdm.eu-central-1.rds.amazonaws.com
        port: 3306
        user: admin
        password: AizdhmakEPQxOts3XvCl
        database: main
    transforms:
      - filterSchema:
          mode: bare
          filters:
            - users_InsertInput.!id