// @ts-nocheck
export default {
  "bets": {
    "TABLE_NAME": "bets",
    "TABLE_TYPE": "BASE TABLE",
    "ENGINE": "InnoDB",
    "VERSION": "10",
    "ROW_FORMAT": "Dynamic",
    "TABLE_ROWS": "0",
    "AVG_ROW_LENGTH": "0",
    "DATA_LENGTH": "16384",
    "MAX_DATA_LENGTH": "0",
    "INDEX_LENGTH": "32768",
    "DATA_FREE": "0",
    "AUTO_INCREMENT": null,
    "CREATE_TIME": "2023-08-31T06:39:10.000Z",
    "UPDATE_TIME": null,
    "CHECK_TIME": null,
    "TABLE_COLLATION": "utf8mb4_0900_ai_ci",
    "CHECKSUM": null,
    "CREATE_OPTIONS": "",
    "TABLE_COMMENT": ""
  },
  "tasks": {
    "TABLE_NAME": "tasks",
    "TABLE_TYPE": "BASE TABLE",
    "ENGINE": "InnoDB",
    "VERSION": "10",
    "ROW_FORMAT": "Dynamic",
    "TABLE_ROWS": "0",
    "AVG_ROW_LENGTH": "0",
    "DATA_LENGTH": "16384",
    "MAX_DATA_LENGTH": "0",
    "INDEX_LENGTH": "16384",
    "DATA_FREE": "0",
    "AUTO_INCREMENT": "1",
    "CREATE_TIME": "2023-08-31T06:22:25.000Z",
    "UPDATE_TIME": null,
    "CHECK_TIME": null,
    "TABLE_COLLATION": "utf8mb4_0900_ai_ci",
    "CHECKSUM": null,
    "CREATE_OPTIONS": "",
    "TABLE_COMMENT": ""
  },
  "users": {
    "TABLE_NAME": "users",
    "TABLE_TYPE": "BASE TABLE",
    "ENGINE": "InnoDB",
    "VERSION": "10",
    "ROW_FORMAT": "Dynamic",
    "TABLE_ROWS": "3",
    "AVG_ROW_LENGTH": "5461",
    "DATA_LENGTH": "16384",
    "MAX_DATA_LENGTH": "0",
    "INDEX_LENGTH": "16384",
    "DATA_FREE": "0",
    "AUTO_INCREMENT": "4",
    "CREATE_TIME": "2023-08-31T06:06:00.000Z",
    "UPDATE_TIME": "2023-09-01T09:04:03.000Z",
    "CHECK_TIME": null,
    "TABLE_COLLATION": "utf8mb4_0900_ai_ci",
    "CHECKSUM": null,
    "CREATE_OPTIONS": "",
    "TABLE_COMMENT": ""
  }
}