defaults:
    run:
      working-directory: backend
on:
    push:
        branches:
            - main
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18.17.1
            - uses: aws-actions/setup-sam@v1
            - uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-central-1
            # - run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 665175433689.dkr.ecr.eu-central-1.amazonaws.com
            # - run: docker build -t betsy-backend .
            # - run: docker tag betsy-backend:latest 665175433689.dkr.ecr.eu-central-1.amazonaws.com/betsy-backend:latest
            # - run: docker push 665175433689.dkr.ecr.eu-central-1.amazonaws.com/betsy-backend:latest

            - run: npm install
              working-directory: ./backend/betsy-backend

            - run: npm install -g esbuild
            # sam build 
            - run: sam build
            
        # Run Unit tests- Specify unit tests here 

        # sam deploy
            - run: sam deploy